### ISSUE TITLE
add AUTHORS.md 

### ISSUE THREAD

**Issue by albedero** [astrojuanlu/ie-mbd-python-statistical-programming#1]
hola astrojuanlu! 
I'm trying to do the optional exercise before session two. I thought i'd only need to input git add AUTHORS.md but that's clearly not the case. so my question what command do i go for and how to i actually add text for the markdown( I'm guessing "" but better safe than sorry)? 
thank you for your help! 
Best,
Alberto

**Comment by astrojuanlu** [comment]
Hello @albedero , I'm catching up and I realized I had missed this notification, sorry! Feel free to open an issue in your Advanced Python repository if you still have questions (and I didn't forget I owe you an email)
